spring:
  application:
    name: Toitter
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
  datasource:
    url: jdbc:mysql://192.168.68.111:3306/test
    username: rinechran
    password: rinechran
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoint:
    health:
      show-details: always