spring:
  application:
    name: Toitter
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
  datasource:
    url: jdbc:mysql://192.168.31.12:3307/test
    username: test
    password: 1
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoint:
    health:
      show-details: always